apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - {{ .Values.pvc.accessModes | toYaml | nindent 6 }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
